type Task {
  id: ID!
  text: String!
  completed: Boolean!
}

input TaskInput {
  text: String!
  completed: Boolean!
}

input UpdateTaskInput {
  text: String
  completed: Boolean
}

type User {
  id: ID!
  email: String!
}

type AuthPayload {
  token: String!
  user: User!
}

type Query {
  allTasks: [Task!]!
  me: User
}

type Mutation {
  signup(email: String!, password: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  logout: Boolean!
  addTask(task: TaskInput!): Task
  updateTask(id: ID!, input: UpdateTaskInput!): Task
  deleteTask(id: ID!): Boolean
}
